import { Language, LanguageStrings } from './languageTypes';

const languageMap: Record<Language, LanguageStrings> = {
  en: {
      logIn: 'Log in',
      loginTitle: 'Log in to your account',
      signUp: 'Sign Up',
      signupTitle: 'Create a nesto account',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      mobilePhoneNumber: 'Mobile phone number',
      password: 'Password',
      confirmpassword: 'Confirm password',
      passwordComplexity: 'Password must be between 12 and 32 characters and contain one uppercase letter, one lowercase letter and one number.',
      agreement: 'By checking this box, you agree to be contacted by nesto’s partners for the purposes of offering you financial products. You agree to nesto sharing your mortgage information with its partners. You can opt-out at any time.',
      readPolicy: 'Read our Privacy Policy to learn more.',
      createYourAccount: 'Create your account',
      createAccountAgreement: 'By clicking on \"Create your account\", I agree and consent to the Terms of Service.',
      province: 'Province',
      al: 'Alberta',
      bc: 'British Columbia',
      mn: 'Manitoba',
      nb: 'New Brunswick',
      nl: 'Newfoundland and Labrador',
      ns: 'Nova Scotia',
      on: 'Ontario',
      qc: 'Quebec',
      pe: 'Prince Edward Island',
      sk: 'Saskatchewan',
      required: 'Required',
      tooManyCharacters: 'Too many characters',
      invalidEmailAddress: 'Invalid email address',
      yourPasswordIsWeak: 'Your password is too weak',
      yourPasswordsDoNotMatch: 'Your passwords do not match'
  },
  fr: {
      logIn: 'Connectez-vous',
      loginTitle: 'Connectez-vous à votre compte',
      signUp: 'Inscrivez-vous',
      signupTitle: 'Créez un compte nesto',
      firstName: 'Prénom',
      lastName: 'Nom de famille',
      email: 'Courriel',
      mobilePhoneNumber: 'Numéro de cellulaire',
      password: 'Mot de passe',
      confirmpassword: 'Confirmez votre mot de passe',
      passwordComplexity: 'Le mot de passe doit comporter entre 12 et 32 caractères et contenir au moins une lettre majuscule, une lettre minuscule et un chiffre.',
      agreement: 'En cochant cette case, vous acceptez d’être contacté par les partenaires de nesto dans le but de vous proposer des produits financiers. Vous acceptez que nesto partage vos informations de demande hypothécaire avec ses partenaires, si nous ne sommes pas en mesure de vous fournir nos services. Vous pouvez vous désinscrire à tout moment.',
      readPolicy: 'Voir notre politique de confidentialité pour en savoir plus.',
      createYourAccount: 'Créez votre compte',
      createAccountAgreement: 'En cliquant sur  \"Créez votre compte\", j\'accepte et consens aux Conditions d\'utilisation.',
      province: 'Province',
      al: 'Alberta',
      bc: 'Colombie-Britannique',
      mn: 'Manitoba',
      nb: 'Nouveau-Brunswick',
      nl: 'Terre-Neuve-et-Labrador',
      ns: 'Nouvelle-Écosse',
      on: 'Ontario',
      qc: 'Québec',
      pe: 'Île-du-Prince-Édouard',
      sk: 'Saskatchewan',
      required: 'Requis',
      tooManyCharacters: 'Trop de caractères',
      invalidEmailAddress: 'Courriel invalide',
      yourPasswordIsWeak: 'Veuillez choisir un mot de passe plus sûr.',
      yourPasswordsDoNotMatch: 'Vos mots de passe ne correspondent pas.'
  }
};

export const getLanguageStrings = (lang: Language): LanguageStrings => {
  return languageMap[lang];
};
